CREATE USER IF NOT EXISTS "SA" SALT '486752943b0b5a8f' HASH '406298ac94f447b18a88a86eabd601233dc8f37903f2fc4d72fe0f6e64dfa754' ADMIN;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_CF050F03_3707_4714_84DD_3BC816503975" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_F3BD7CBB_7C3C_420B_906E_8D45386CDE36" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D9D1B0B2_9D4D_401C_94AC_FD7BF7C2E3B9" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_5EEEB504_4A3B_4DD4_8ADC_1FAB7B3AFDE6" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_3A89276A_D7EE_4BDE_8ECE_C6C8BD6B80F7" START WITH 1 BELONGS_TO_TABLE;
CREATE MEMORY TABLE "PUBLIC"."ORGANIZATION"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_5EEEB504_4A3B_4DD4_8ADC_1FAB7B3AFDE6" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_5EEEB504_4A3B_4DD4_8ADC_1FAB7B3AFDE6",
    "ORGANIZATION_ADDRESS" VARCHAR(255),
    "ORGANIZATION_NAME" VARCHAR(255),
    "ORGANIZATION_ID" VARCHAR(255),
    "ORGANIZATION_PHONE_NUMBER" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."ORGANIZATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORGANIZATION;
CREATE MEMORY TABLE "PUBLIC"."OTP"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_CF050F03_3707_4714_84DD_3BC816503975" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_CF050F03_3707_4714_84DD_3BC816503975",
    "DATE_TIME" TIMESTAMP,
    "OTP" VARCHAR(255),
    "OTP_ID" VARCHAR(255),
    "STATUS" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."OTP" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.OTP;
CREATE MEMORY TABLE "PUBLIC"."REL_OTP_USER"(
    "USER_ID" BIGINT,
    "OTP_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_OTP_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("OTP_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_OTP_USER;
CREATE MEMORY TABLE "PUBLIC"."REL_TASK_ORGANIZATION"(
    "ORGANIZATION_ID" BIGINT,
    "TASK_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_TASK_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D7" PRIMARY KEY("TASK_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_TASK_ORGANIZATION;
CREATE MEMORY TABLE "PUBLIC"."REL_TASK_USER"(
    "USER_ID" BIGINT,
    "TASK_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_TASK_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("TASK_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_TASK_USER;
CREATE MEMORY TABLE "PUBLIC"."REL_USER_ORGANIZATION"(
    "ORGANIZATION_ID" BIGINT,
    "USER_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_USER_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_47" PRIMARY KEY("USER_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_USER_ORGANIZATION;
CREATE MEMORY TABLE "PUBLIC"."REL_USER_ROLE"(
    "USER_ID" BIGINT NOT NULL,
    "ROLE_ID" BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_USER_ROLE;
CREATE MEMORY TABLE "PUBLIC"."ROLE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_F3BD7CBB_7C3C_420B_906E_8D45386CDE36" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_F3BD7CBB_7C3C_420B_906E_8D45386CDE36",
    "ROLE_NAME" VARCHAR(255),
    "ROLE_ID" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."ROLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ROLE;
CREATE MEMORY TABLE "PUBLIC"."TASK"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_D9D1B0B2_9D4D_401C_94AC_FD7BF7C2E3B9" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D9D1B0B2_9D4D_401C_94AC_FD7BF7C2E3B9",
    "TASK_DEADLINE" VARCHAR(255),
    "TASK_DESCRIPTION" VARCHAR(255),
    "TASK_STATUS" VARCHAR(255),
    "TASK_ID" VARCHAR(255),
    "TASK_TITLE" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."TASK" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_27" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TASK;
CREATE MEMORY TABLE "PUBLIC"."USER"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_3A89276A_D7EE_4BDE_8ECE_C6C8BD6B80F7" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_3A89276A_D7EE_4BDE_8ECE_C6C8BD6B80F7",
    "USER_EMAIL" VARCHAR(255),
    "USER_NAME" VARCHAR(255),
    "USER_PASSWORD" VARCHAR(255),
    "USER_STATUS" VARCHAR(255),
    "USER_SURNAME" VARCHAR(255),
    "USER_ID" VARCHAR(255),
    "USER_USERNAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_27E" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER;
ALTER TABLE "PUBLIC"."REL_OTP_USER" ADD CONSTRAINT "PUBLIC"."FKRMEBCVV1LNWF8P2SEDR4MQG9W" FOREIGN KEY("OTP_ID") REFERENCES "PUBLIC"."OTP"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_USER_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."FKJL8Y94CCWWJJ0Y5A8JB8UJVJK" FOREIGN KEY("ORGANIZATION_ID") REFERENCES "PUBLIC"."ORGANIZATION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_USER_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."FK8RT3U9BJI1RRX0D667LDQ43ES" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_USER_ROLE" ADD CONSTRAINT "PUBLIC"."FK1UXDUYL9A5VAA3269V64SEYE" FOREIGN KEY("ROLE_ID") REFERENCES "PUBLIC"."ROLE"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_TASK_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."FKQRV0C45TEW8VQB0EHXT4DIIQO" FOREIGN KEY("ORGANIZATION_ID") REFERENCES "PUBLIC"."ORGANIZATION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_TASK_USER" ADD CONSTRAINT "PUBLIC"."FKJ5L9QTXQOODI23NWE4UNKJPRI" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_OTP_USER" ADD CONSTRAINT "PUBLIC"."FK2FRHWS9J0FFPQ6N3U2O4WBEBJ" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_TASK_USER" ADD CONSTRAINT "PUBLIC"."FK5TW58JP4W8X0RITYP6UEFL7J9" FOREIGN KEY("TASK_ID") REFERENCES "PUBLIC"."TASK"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_TASK_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."FK2A45S9BWNH8TV7BDHGT8FGYRW" FOREIGN KEY("TASK_ID") REFERENCES "PUBLIC"."TASK"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_USER_ROLE" ADD CONSTRAINT "PUBLIC"."FKNEXCJSRTBMNHYYJ4V8RRBHE6I" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;