CREATE USER IF NOT EXISTS "SA" SALT '3808aeddbece6b5d' HASH '1c442859d92f75e6c535be6a6159be0b47fd14c5a16aa027cb246155e68d43d8' ADMIN;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_C7F39A4E_27C2_476F_B2DB_08A2BAE52078" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_39A58C43_91F9_45D1_B052_739B15A518DB" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_DB3E01C6_A137_4288_9219_8107017250ED" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_7963BD5F_7FC4_476F_B6B4_7A81F3B5C748" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_C46B406B_CBF8_4E72_95CE_1932E5240CA9" START WITH 1 BELONGS_TO_TABLE;
CREATE MEMORY TABLE "PUBLIC"."ORGANIZATION"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_39A58C43_91F9_45D1_B052_739B15A518DB" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_39A58C43_91F9_45D1_B052_739B15A518DB",
    "ORGANIZATION_ADDRESS" VARCHAR(255),
    "ORGANIZATION_NAME" VARCHAR(255),
    "ORGANIZATION_ID" VARCHAR(255),
    "ORGANIZATION_PHONE_NUMBER" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."ORGANIZATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORGANIZATION;
CREATE MEMORY TABLE "PUBLIC"."OTP"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_C46B406B_CBF8_4E72_95CE_1932E5240CA9" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_C46B406B_CBF8_4E72_95CE_1932E5240CA9",
    "DATE_TIME" TIMESTAMP,
    "OTP" VARCHAR(255),
    "OTP_ID" VARCHAR(255),
    "STATUS" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."OTP" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.OTP;
CREATE MEMORY TABLE "PUBLIC"."REL_OTP_WITH_USER"(
    "USER_ID" BIGINT,
    "OTP_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_OTP_WITH_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("OTP_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_OTP_WITH_USER;
CREATE MEMORY TABLE "PUBLIC"."REL_ROLE_USER"(
    "USER_ID" BIGINT,
    "ROLE_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_ROLE_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ROLE_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_ROLE_USER;
CREATE MEMORY TABLE "PUBLIC"."REL_TASK_ORGANIZATION"(
    "ORGANIZATION_ID" BIGINT,
    "TASK_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_TASK_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D7" PRIMARY KEY("TASK_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_TASK_ORGANIZATION;
CREATE MEMORY TABLE "PUBLIC"."REL_TASK_USER"(
    "USER_ID" BIGINT,
    "TASK_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_TASK_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("TASK_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_TASK_USER;
CREATE MEMORY TABLE "PUBLIC"."REL_USER_ORGANIZATION"(
    "ORGANIZATION_ID" BIGINT,
    "USER_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_USER_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_47" PRIMARY KEY("USER_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_USER_ORGANIZATION;
CREATE MEMORY TABLE "PUBLIC"."ROLE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_7963BD5F_7FC4_476F_B6B4_7A81F3B5C748" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_7963BD5F_7FC4_476F_B6B4_7A81F3B5C748",
    "ROLE_NAME" VARCHAR(255),
    "ROLE_ID" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."ROLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ROLE;
CREATE MEMORY TABLE "PUBLIC"."TASK"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_DB3E01C6_A137_4288_9219_8107017250ED" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_DB3E01C6_A137_4288_9219_8107017250ED",
    "TASK_DEADLINE" VARCHAR(255),
    "TASK_DESCRIPTION" VARCHAR(255),
    "TASK_STATUS" VARCHAR(255),
    "TASK_ID" VARCHAR(255),
    "TASK_TITLE" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."TASK" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_27" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TASK;
CREATE MEMORY TABLE "PUBLIC"."USER"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_C7F39A4E_27C2_476F_B2DB_08A2BAE52078" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_C7F39A4E_27C2_476F_B2DB_08A2BAE52078",
    "USER_EMAIL" VARCHAR(255),
    "USER_NAME" VARCHAR(255),
    "USER_PASSWORD" VARCHAR(255),
    "USER_SURNAME" VARCHAR(255),
    "USER_ID" VARCHAR(255),
    "USER_USERNAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_27E" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER;
ALTER TABLE "PUBLIC"."REL_OTP_WITH_USER" ADD CONSTRAINT "PUBLIC"."FKRMEBCVV1LNWF8P2SEDR4MQG9W" FOREIGN KEY("OTP_ID") REFERENCES "PUBLIC"."OTP"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_USER_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."FKJL8Y94CCWWJJ0Y5A8JB8UJVJK" FOREIGN KEY("ORGANIZATION_ID") REFERENCES "PUBLIC"."ORGANIZATION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_ROLE_USER" ADD CONSTRAINT "PUBLIC"."FKI5AGI2BA298G2XH9UOYM2OUQR" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_USER_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."FK8RT3U9BJI1RRX0D667LDQ43ES" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_ROLE_USER" ADD CONSTRAINT "PUBLIC"."FKF44MFMC4BAWUO34WMTUWNX4U3" FOREIGN KEY("ROLE_ID") REFERENCES "PUBLIC"."ROLE"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_TASK_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."FKQRV0C45TEW8VQB0EHXT4DIIQO" FOREIGN KEY("ORGANIZATION_ID") REFERENCES "PUBLIC"."ORGANIZATION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_TASK_USER" ADD CONSTRAINT "PUBLIC"."FKJ5L9QTXQOODI23NWE4UNKJPRI" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_OTP_WITH_USER" ADD CONSTRAINT "PUBLIC"."FK2FRHWS9J0FFPQ6N3U2O4WBEBJ" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_TASK_USER" ADD CONSTRAINT "PUBLIC"."FK5TW58JP4W8X0RITYP6UEFL7J9" FOREIGN KEY("TASK_ID") REFERENCES "PUBLIC"."TASK"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_TASK_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."FK2A45S9BWNH8TV7BDHGT8FGYRW" FOREIGN KEY("TASK_ID") REFERENCES "PUBLIC"."TASK"("ID") NOCHECK;