CREATE USER IF NOT EXISTS "SA" SALT 'ed591c749b462da9' HASH '85b4f1e82ee0ae449c57fa84adcd6ec0713d33b570079407eaa55f4d508224b7' ADMIN;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_41DA6D25_F882_4669_B0D4_193DB83714B1" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_6B96FA05_310B_48A9_B7E5_2CC8480EB50B" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_526CCCD2_69F5_43AE_BB72_333B79D734DF" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_FADCF366_B87C_4EFF_8526_9692796FA516" START WITH 1 BELONGS_TO_TABLE;
CREATE MEMORY TABLE "PUBLIC"."ORGANIZATION"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_6B96FA05_310B_48A9_B7E5_2CC8480EB50B" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_6B96FA05_310B_48A9_B7E5_2CC8480EB50B",
    "ORGANIZATION_ADDRESS" VARCHAR(255),
    "ORGANIZATION_NAME" VARCHAR(255),
    "ORGANIZATION_ID" VARCHAR(255),
    "ORGANIZATION_PASSWORD" VARCHAR(255),
    "ORGANIZATION_PHONE_NUMBER" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."ORGANIZATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");

CREATE MEMORY TABLE "PUBLIC"."REL_ROLE_USER"(
    "USER_ID" BIGINT,
    "ROLE_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_ROLE_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ROLE_ID");

CREATE MEMORY TABLE "PUBLIC"."REL_TASK_ORGANIZATION"(
    "ORGANIZATION_ID" BIGINT,
    "TASK_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_TASK_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D7" PRIMARY KEY("TASK_ID");

CREATE MEMORY TABLE "PUBLIC"."REL_TASK_USER"(
    "USER_ID" BIGINT,
    "TASK_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_TASK_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("TASK_ID");

CREATE MEMORY TABLE "PUBLIC"."REL_USER_ORGANIZATION"(
    "ORGANIZATION_ID" BIGINT,
    "USER_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_USER_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("USER_ID");

CREATE MEMORY TABLE "PUBLIC"."ROLE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_FADCF366_B87C_4EFF_8526_9692796FA516" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_FADCF366_B87C_4EFF_8526_9692796FA516",
    "ROLE_NAME" VARCHAR(255),
    "ROLE_ID" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."ROLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");

CREATE MEMORY TABLE "PUBLIC"."TASK"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_41DA6D25_F882_4669_B0D4_193DB83714B1" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_41DA6D25_F882_4669_B0D4_193DB83714B1",
    "TASK_DEADLINE" VARCHAR(255),
    "TASK_DESCRIPTION" VARCHAR(255),
    "TASK_STATUS" VARCHAR(255),
    "TASK_ID" VARCHAR(255),
    "TASK_TITLE" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."TASK" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_27" PRIMARY KEY("ID");

CREATE MEMORY TABLE "PUBLIC"."USER"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_526CCCD2_69F5_43AE_BB72_333B79D734DF" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_526CCCD2_69F5_43AE_BB72_333B79D734DF",
    "USER_EMAIL" VARCHAR(255),
    "USER_NAME" VARCHAR(255),
    "USER_PASSWORD" VARCHAR(255),
    "USER_SURNAME" VARCHAR(255),
    "USER_ID" VARCHAR(255),
    "USER_USERNAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_27E" PRIMARY KEY("ID");

ALTER TABLE "PUBLIC"."REL_USER_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."FKJL8Y94CCWWJJ0Y5A8JB8UJVJK" FOREIGN KEY("ORGANIZATION_ID") REFERENCES "PUBLIC"."ORGANIZATION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_ROLE_USER" ADD CONSTRAINT "PUBLIC"."FKI5AGI2BA298G2XH9UOYM2OUQR" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_USER_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."FK8RT3U9BJI1RRX0D667LDQ43ES" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_ROLE_USER" ADD CONSTRAINT "PUBLIC"."FKF44MFMC4BAWUO34WMTUWNX4U3" FOREIGN KEY("ROLE_ID") REFERENCES "PUBLIC"."ROLE"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_TASK_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."FKQRV0C45TEW8VQB0EHXT4DIIQO" FOREIGN KEY("ORGANIZATION_ID") REFERENCES "PUBLIC"."ORGANIZATION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_TASK_USER" ADD CONSTRAINT "PUBLIC"."FKJ5L9QTXQOODI23NWE4UNKJPRI" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_TASK_USER" ADD CONSTRAINT "PUBLIC"."FK5TW58JP4W8X0RITYP6UEFL7J9" FOREIGN KEY("TASK_ID") REFERENCES "PUBLIC"."TASK"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_TASK_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."FK2A45S9BWNH8TV7BDHGT8FGYRW" FOREIGN KEY("TASK_ID") REFERENCES "PUBLIC"."TASK"("ID") NOCHECK;
